### ISSUE TITLE
链接和样式全部是坏的

### ISSUE THREAD

**Issue by forsigner** [jiyinyiyong/tiye.me#12]
链接和样式全部是坏的：
![image](https://user-images.githubusercontent.com/2668081/117386487-9a239b00-af19-11eb-8d9a-ffc274f5f535.png)

**Comment by jiyinyiyong** [comment]
唉 https://github.com/tiye/tiye.me/pull/13 , 应该好了.

**Comment by newraina** [comment]
没有完全好，页面中文有乱码

**Comment by jiyinyiyong** [comment]
没有 windows 测试机, 也只能随便修修了

**Comment by forsigner** [comment]
昨天 mac 也是乱码，貌似今天好了

**Comment by jiyinyiyong** [comment]
刚才修了一下. 估计 utf8 编码配置问题.
